ISM.WebApp/Models/CurrentAccomodation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ISM.WebApp.Models
{
    public class CurrentAccomodation
    {
        public int? current_accomodation_id { get; set; }
        public User student { get; set; }
        public StudentGroup student_group { get; set; }
        public string type { get; set; }
        public string location { get; set; }
        public string description { get; set; }
        public double? fee { get; set; }
        public string picture { get; set; }
        public string note { get; set; }
    }
}

ISM.WebApp/Models/StudentHandbook.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ISM.WebApp.Models
{
    public class StudentHandbook
    {
        public int student_handbook_id { get; set; }
        public int campus_id { get; set; }
        public string title { get; set; }
        public string file_name { get; set; }
    }
}

ISM.WebApp/ViewModels/GeneralAgendaDetailViewModel.cs
using ISM.WebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ISM.WebApp.ViewModels
{
    public class GeneralAgendaDetailViewModel
    {
        public StudentGroup current_student_group { get; set; }
        public GeneralAgenda generalAgenda { get; set; }
    }
}

ISM.WebApp/Controllers/CurrentAccomodationController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ISM.WebApp.Constant;
using ISM.WebApp.DAO;
using ISM.WebApp.Models;
using ISM.WebApp.Utils;
using ISM.WebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ISM.WebApp.Controllers
{
    [Authorize(Roles = "Admin,Staff,Degree,Mobility")]
    public class CurrentAccomodationController : Controller
    {
        public StudentGroupDAO StudentGroupDAO;
        public AccomodationDAO accomodationDAO;
        public UserDAO userDAO;
        private readonly IWebHostEnvironment hostingEnvironment;

        public CurrentAccomodationController(StudentGroupDAO studentGroupDAO, AccomodationDAO accomodationDAO, UserDAO userDAO, IWebHostEnvironment hostingEnvironment)
        {
            this.StudentGroupDAO = studentGroupDAO;
            this.accomodationDAO = accomodationDAO;
            this.userDAO = userDAO;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index(string degreeOrMobility="",string account="",string fullname="",int? student_id=null,int? student_group_id=null,string type="",string location="",string description="",string note="",int page=1)
        {
            Account sessionUser = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString(LoginConst.SessionKeyName));
            if (sessionUser.role_name.Equals("Admin") || sessionUser.role_name.Equals("Staff"))
            {
                bool isAdmin = sessionUser.role_name.Equals("Admin") ? true : false;
                bool haveDegree = isAdmin == true ? true : sessionUser.haveDegree;
                int current_staff_id = sessionUser.user_id;
                if (string.IsNullOrEmpty(degreeOrMobility))
                {
                    if (haveDegree)
                    {
                        degreeOrMobility = "Degree";
                    }
                    else
                    {
                        degreeOrMobility = "Mobility";
                    }
                }
                CurrentAccomodationIndexViewModel view = new CurrentAccomodationIndexViewModel();
                view.page = page;
                view.pageSize = pagingConst.PAGE_SIZE;
                view.totalPage = PagingUtils.calculateTotalPage(accomodationDAO.getTotalCurrentAccomodations(isAdmin, haveDegree, degreeOrMobility, current_staff_id, account, fullname, student_id, student_group_id, type, location, description, note), view.pageSize);
                view.currentAccomodations = accomodationDAO.GetCurrentAccomodations(isAdmin, haveDegree, degreeOrMobility, current_staff_id, view.page, view.pageSize, account, fullname, student_id, student_group_id, type, location, description, note);
                view.degreeStudents = userDAO.getAllDegreeStudents();
                view.manageGroup = StudentGroupDAO.GetStudentGroupByStaff(current_staff_id, isAdmin, "Mobility");
                view.account = account;
                view.fullname = fullname;
                view.type = type;
                view.location = location;
                view.description = description;
                view.note = note;
                view.student_id = student_id;
                view.student_group_id = student_group_id;
                view.degreeOrMobility = degreeOrMobility;
                return View("Views/Admin/CurrentAccomodation/Index.cshtml", view);
            }
            else if(sessionUser.role_name.Equals("Degree") || sessionUser.role_name.Equals("Mobility"))
            {
                CurrentAccomodationIndexViewModel view = new CurrentAccomodationIndexViewModel();
                if (sessionUser.role_name.Equals("Degree"))
                {
                    view.student_current_accomodation = accomodationDAO.GetCurrentAccomodation(sessionUser.user_id, null);
                }
                else if(sessionUser.role_name.Equals("Mobility"))
                {
                    view.student_current_accomodation = accomodationDAO.GetCurrentAccomodation(null, sessionUser.student_group_id);
                }
                return View("Views/Degree/PreDeparture/CurrentAccomodation.cshtml", view);
            }
            return View();
        }

        [Authorize(Roles = "Admin,Staff")]
        public IActionResult Create(int? student_id, int? student_group_id, string type, string location, string description, double? fee, string note, IFormFile picture)
        {
            string pictureName = "";
            if (picture != null)
            {
                string extension = Path.GetExtension(picture.FileName);
                if (student_id != null)
                {
                    pictureName = "student_" + student_id;
                    pictureName += extension;
                }
                else if(student_group_id != null)
                {
                    pictureName = "studentGroup_" + student_group_id;
                    pictureName += extension;
                }
                string image = Path.Combine(hostingEnvironment.WebRootPath, "image");
                string currentAccomodation = Path.Combine(image, "CurrentAccomodation");
                string filePath = Path.Combine(currentAccomodation, pictureName);
                FileStream stream = new FileStream(filePath, FileMode.Create);
                picture.CopyTo(stream);
                stream.Close();
            }
            bool result = accomodationDAO.createCurrentAccomodation(student_id, student_group_id, type, location, description, fee, pictureName, note);
            if (result == false)
            {
                return Json(new { status = "error", message = "Create Failed" });
            }
            return Json(new { status = "success", message = "Create successfully" });
        }

        [Authorize(Roles = "Admin,Staff")]
        public IActionResult Edit(int? student_id, int? student_group_id, int current_accomodation_id, string type, string location, string description, double? fee, string note, IFormFile picture, string pictureName)
        {
            if (picture != null)
            {
                string extension = Path.GetExtension(picture.FileName);
                if (student_id != null)
                {
                    pictureName = "student_" + student_id;
                    pictureName += extension;
                }
                else if (student_group_id != null)
                {
                    pictureName = "studentGroup_" + student_group_id;
                    pictureName += extension;
                }
                string image = Path.Combine(hostingEnvironment.WebRootPath, "image");
                string currentAccomodation = Path.Combine(image, "CurrentAccomodation");
                string filePath = Path.Combine(currentAccomodation, pictureName);
                FileStream stream = new FileStream(filePath, FileMode.Create);
                picture.CopyTo(stream);
                stream.Close();
            }
            bool result = accomodationDAO.editCurrentAccomodation(current_accomodation_id, type, location, description, fee, pictureName, note);
            if (result == false)
            {
                return Json(new { status = "error", message = "Edit Failed" });
            }
            return Json(new { status = "success", message = "Edit successfully" });
        }

        [Authorize(Roles = "Admin,Staff")]
        public bool isCurrentAccomodationExist(int? student_id, int? student_group_id)
        {
            bool result=accomodationDAO.isCurrentAccomodationExist(student_id, student_group_id);
            return result;
        }

        [Authorize(Roles = "Admin,Staff")]
        public bool SetupNotification(int days_before)
        {
            bool result = accomodationDAO.SetupNotification(days_before);
            return result;
        }
    }
}

ISM.WebApp/Controllers/StudentHandbookController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ISM.WebApp.Constant;
using ISM.WebApp.DAO;
using ISM.WebApp.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ISM.WebApp.Controllers
{
    [Authorize(Roles = "Admin,Staff,Degree,Mobility")]
    public class StudentHandbookController : Controller
    {
        public StudentHandbookDAO studentHandbookDAO;
        private readonly IWebHostEnvironment hostingEnvironment;
        public StudentHandbookController(StudentHandbookDAO studentHandbookDAO, IWebHostEnvironment hostingEnvironment)
        {
            this.studentHandbookDAO = studentHandbookDAO;
            this.hostingEnvironment = hostingEnvironment;
        }
        public IActionResult Index()
        {
            Account sessionUser = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString(LoginConst.SessionKeyName));
            List<StudentHandbook> studentHandbooks = studentHandbookDAO.getAllStudentHandbook();
            if (sessionUser.role_name.Equals("Admin") || sessionUser.role_name.Equals("Staff"))
            {
                return View("Views/Admin/Pre-Departure/StudentHandbook.cshtml", studentHandbooks);
            }
            else if(sessionUser.role_name.Equals("Degree") || sessionUser.role_name.Equals("Mobility"))
            {
                return View("Views/Degree/PreDeparture/StudentHandbook.cshtml", studentHandbooks);
            }
            return View();
        }

        public IActionResult Detail(int id)
        {
            Account sessionUser = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString(LoginConst.SessionKeyName));
            StudentHandbook studentHandbook = studentHandbookDAO.GetStudentHandbookById(id);
            if (sessionUser.role_name.Equals("Admin") || sessionUser.role_name.Equals("Staff"))
            {
                return View("Views/Admin/Pre-Departure/StudentHandbookDetail.cshtml", studentHandbook);
            }
            else if (sessionUser.role_name.Equals("Degree") || sessionUser.role_name.Equals("Mobility"))
            {
                return View("Views/Degree/PreDeparture/StudentHandbookDetail.cshtml", studentHandbook);
            }
            return View();
        }

        [Authorize(Roles = "Admin,Staff")]
        public IActionResult Edit(int student_handbook_id, string title, IFormFile file)
        {
            string file_name = "student_handbook_" + student_handbook_id + ".pdf";
            if (file != null)
            {
                string article = Path.Combine(hostingEnvironment.WebRootPath, "Article");
                string subfolderPath = Path.Combine(article, "Student Handbook");
                string filePath = Path.Combine(subfolderPath, file_name);
                FileStream stream = new FileStream(filePath, FileMode.Create);
                file.CopyTo(stream);
                stream.Close();
            }
            bool result = studentHandbookDAO.editStudentHandbook(student_handbook_id, title, file_name);
            if (result == false)
            {
                return Json(new { status = "error", message = "Edit Failed" });
            }
            return Json(new { status = "success", message = "Edit successfully" });
        }
    }
}

ISM.WebApp/Views/Degree/PreDeparture/CurrentAccomodation.cshtml
@model ISM.WebApp.ViewModels.CurrentAccomodationIndexViewModel
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using ISM.WebApp.Constant;
@{
    var sessionUser = JsonConvert.DeserializeObject<Account>(Context.Session.GetString(LoginConst.SessionKeyName));
    if (sessionUser.role_name == "Degree")
    {
        ViewData["Title"] = "Pre-Approval Visa Page";
        Layout = "~/Views/Shared/_DegreeStudentLayout.cshtml";
    }
    else if (sessionUser.role_name == "Mobility")
    {
        ViewData["Title"] = "Pre-Approval Visa  Page";
        Layout = "~/Views/Shared/_MobilityStudentLayout.cshtml";
    }
}

<h1 style="text-align:center">Current Accommodation</h1>
<br />
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <img src="~/image/CurrentAccomodation/@Model.student_current_accomodation.picture" class="rounded float-left" style="width: 300px; height: 300px;" asp-append-version="true">
        </div>
        <div class="col-md-8">
            <form>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Type:</label>
                    <input type="text" style="width: 300px; margin-left: 30px; border-radius: 5px;" value="@Model.student_current_accomodation.type" disabled>
                </div>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Location:</label>
                    <input type="text" style="width: 300px; margin-left: 30px; border-radius: 5px;" value="@Model.student_current_accomodation.location" disabled>
                </div>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Description:</label>
                    <input type="text" style="width: 300px; margin-left: 30px; border-radius: 5px;" value="@Model.student_current_accomodation.description" disabled>
                </div>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Fee:</label>
                    <input type="text" style="width: 300px; margin-left: 30px; border-radius: 5px;" value="@Model.student_current_accomodation.fee" disabled>
                </div>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Note:</label>
                    <input type="text" style="width: 300px; margin-left: 30px; border-radius: 5px;" value="@Model.student_current_accomodation.note" disabled>
                </div>                             
            </form>
        </div>
    </div>
</div>

ISM.WebApp/Views/Degree/PreDeparture/GeneralAgendaDetail.cshtml
@model ISM.WebApp.ViewModels.GeneralAgendaDetailViewModel
@{
    ViewData["Title"] = "Pre-Approval Visa  Page";
    Layout = "~/Views/Shared/_MobilityStudentLayout.cshtml";
}

<h1 style="text-align: center;"> General Agenda </h1>
<div style="height:50px">

</div>
<br>
<br>
<div>
    <a href="~/GeneralAgenda/@Model.generalAgenda.content" style="font-size:18px;" download="General Agenda">Download General Agenda</a>
    <h3>Note:</h3>
    <p style="font-size:16px;">@Model.generalAgenda.note</p>
</div>

<script>function myFunction() {
        document.getElementById("myDropdown").classList.toggle("show");
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn')) {
            var dropdowns = document.getElementsByClassName("dropdown-content");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }

    // Close the dropdown if the user clicks outside of it
    window.onclick = function (event) {
        if (!event.target.matches('.dropbtn_search')) {
            var dropdowns = document.getElementsByClassName("dropdown-content_search");
            var i;
            for (i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show_search')) {
                    openDropdown.classList.remove('show_search');
                }
            }
        }
    }

    function search_visa() {
        document.getElementById("myDropdown_search").classList.toggle("show_search_visa");
    }

    function filterFunction() {
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("myDropdown_search");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "none";
            }
        }
    }</script>

ISM.WebApp/Views/Degree/PreDeparture/StudentHandbook.cshtml
@model IEnumerable<ISM.WebApp.Models.StudentHandbook>
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using ISM.WebApp.Constant;
@{
    var sessionUser = JsonConvert.DeserializeObject<Account>(Context.Session.GetString(LoginConst.SessionKeyName));
    if (sessionUser.role_name == "Degree")
    {
        ViewData["Title"] = "Pre-Approval Visa Page";
        Layout = "~/Views/Shared/_DegreeStudentLayout.cshtml";
    }
    else if (sessionUser.role_name == "Mobility")
    {
        ViewData["Title"] = "Pre-Approval Visa  Page";
        Layout = "~/Views/Shared/_MobilityStudentLayout.cshtml";
    }
}
<div style="height: 500px; background-color: white;">
    <h1 style="text-align: center;">Student's Handbook</h1>
    @foreach (var item in Model)
    {
        <a asp-controller="StudentHandbook" asp-action="Detail" asp-route-id="@item.student_handbook_id">@item.title</a>
        <br />
    }
</div>

ISM.WebApp/Views/Degree/PreDeparture/StudentHandbookDetail.cshtml
@model ISM.WebApp.Models.StudentHandbook
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using ISM.WebApp.Constant;
@{
    var sessionUser = JsonConvert.DeserializeObject<Account>(Context.Session.GetString(LoginConst.SessionKeyName));
    if (sessionUser.role_name == "Degree")
    {
        ViewData["Title"] = "Pre-Approval Visa Page";
        Layout = "~/Views/Shared/_DegreeStudentLayout.cshtml";
    }
    else if (sessionUser.role_name == "Mobility")
    {
        ViewData["Title"] = "Pre-Approval Visa  Page";
        Layout = "~/Views/Shared/_MobilityStudentLayout.cshtml";
    }
}

<h1 style="text-align: center;">@Model.title</h1>
<div style="height: 50px;">

</div>

<a href="~/Article/Student Handbook/@Model.file_name" style="font-size:24px;" download="@Model.title">download file</a>
<br />
<h1>Preview</h1>
<br />
<div id="pdf-main-container">
    <div id="pdf-loader">
        <div id="pdf-loading-bar"><div id="pdf-loading-completed"></div></div>
    </div>
    <div id="pdf-contents">
        <div class="top-bar">
            <button class="btn prev-page">
                <i class="fas fa-arrow-circle-left"></i> Prev Page
            </button>
            <button class="btn next-page">
                Next Page <i class="fas fa-arrow-circle-right"></i>
            </button>
            <span class="page-info">
                Page <span class="page-num"></span> of <span class="page-count"></span>
            </span>
        </div>
        <br />
        <div id="page-loader" style="height:100%; font-size:30px;">Loading page ...</div>
        <canvas id="pdf-canvas" style="width:100%;"></canvas>
        <div class="top-bar">
            <button class="btn prev-page">
                <i class="fas fa-arrow-circle-left"></i> Prev Page
            </button>
            <button class="btn next-page">
                Next Page <i class="fas fa-arrow-circle-right"></i>
            </button>
            <span class="page-info">
                Page <span class="page-num"></span> of <span class="page-count"></span>
            </span>
        </div>
    </div>
</div>

<script>

    var url = '../../Article/Student Handbook/@Model.file_name?' + performance.now();

    var pdfDoc = null,
        pageNum = 1,
        pageIsRendering = false,
        pageNumIsPending = null,
        scale = 4,
        canvas = document.getElementById('pdf-canvas'),
        ctx = canvas.getContext('2d');

    // Render the page
    var renderPage = num => {
        pageIsRendering = true;
        $("#pdf-canvas").hide();
        $("#page-loader").show();
        // Get page
        pdfDoc.getPage(num).then(page => {
            // Set scale
            var viewport = page.getViewport({ scale });
            canvas.height = viewport.height;
            canvas.width = viewport.width;
            $("#page-loader").height(viewport.height);

            var renderCtx = {
                canvasContext: ctx,
                viewport
            };

            page.render(renderCtx).promise.then(() => {
                pageIsRendering = false;
                if (pageNumIsPending !== null) {
                    renderPage(pageNumIsPending);
                    pageNumIsPending = null;
                }
                $("#pdf-canvas").show();
                $("#page-loader").hide();
            });

            // Output current page
            $(".page-num").text(num);
        });
    };

    // Check for pages rendering
    var queueRenderPage = num => {
        if (pageIsRendering) {
            pageNumIsPending = num;
        } else {
            renderPage(num);
        }
    };

    //load document
    var loadingTask = pdfjsLib.getDocument(url);

    //get progress data
    loadingTask.onProgress = function (data) {
        var percent_loaded = (data.loaded / data.total) * 100;
        $("#pdf-loading-completed").css('width', percent_loaded + '%');
    }

    $("#pdf-loader").show();
    loadingTask.promise.then(function (pdfDoc_) {
        pdfDoc = pdfDoc_;
        $(".page-count").text(pdfDoc.numPages);
        $("#pdf-loader").hide();
        $("#pdf-contents").show();
        renderPage(pageNum);
    }).catch(err => {
        // Display error
        $("#pdf-loader").hide();
        var div = document.createElement('div');
        div.className = 'error';
        div.appendChild(document.createTextNode(err.message));
        document.querySelector('body').insertBefore(div, canvas);
        // Remove top bar
        document.querySelector('.top-bar').style.display = 'none';
    });

    // Button Events
    $(".prev-page").on('click', function () {
        if (pageNum <= 1) {
            return;
        }
        pageNum--;
        queueRenderPage(pageNum);
    });

    $(".next-page").on('click', function () {
        if (pageNum >= pdfDoc.numPages) {
            return;
        }
        pageNum++;
        queueRenderPage(pageNum);
    });

</script>