ISM.WebApp/Models/FAQ.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ISM.WebApp.Models
{
    public class FAQ
    {
        public int faq_id { get; set; }
        public string question { get; set; }
        public string answer { get; set; }
    }
}

ISM.WebApp/Controllers/FAQController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ISM.WebApp.Constant;
using ISM.WebApp.DAO;
using ISM.WebApp.Models;
using ISM.WebApp.Utils;
using ISM.WebApp.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace ISM.WebApp.Controllers
{
    [Authorize(Roles = "Admin,Staff,Degree,Mobility")]
    public class FAQController : Controller
    {
        public FAQDAO fAQDAO;
        public FAQController(FAQDAO fAQDAO)
        {
            this.fAQDAO = fAQDAO;
        }
        public IActionResult Index(string question=null,string answer=null,int page=1)
        {
            Account sessionUser = JsonConvert.DeserializeObject<Account>(HttpContext.Session.GetString(LoginConst.SessionKeyName));
            FAQIndexViewModel view = new FAQIndexViewModel();
            view.page = page;
            view.pageSize = pagingConst.PAGE_SIZE;
            view.totalPage = PagingUtils.calculateTotalPage(fAQDAO.getTotalFAQ(question, answer), view.pageSize);
            view.faqs = fAQDAO.getFAQ(view.page, view.pageSize, question, answer);
            view.question = question;
            view.answer = answer;
            if (sessionUser.role_name.Equals("Admin") || sessionUser.role_name.Equals("Staff"))
            {
                return View("Views/Admin/FAQs/FAQs.cshtml", view);
            }
            else if (sessionUser.role_name.Equals("Degree") || sessionUser.role_name.Equals("Mobility")) {
                return View("Views/Degree/FAQs/FAQs.cshtml", view);
            }
            return View();
        }

        [Authorize(Roles = "Admin,Staff")]
        public bool Create(string question, string answer)
        {
            bool result = fAQDAO.createFAQ(question, answer);
            return result;
        }

        [Authorize(Roles = "Admin,Staff")]
        public bool Edit(int faq_id, string question, string answer)
        {
            bool result = fAQDAO.editFAQ(faq_id, question, answer);
            return result;
        }

        [Authorize(Roles = "Admin,Staff")]
        public bool Delete(int faq_id)
        {
            bool result = fAQDAO.deleteFAQ(faq_id);
            return result;
        }
    }
}

ISM.WebApp/Views/Degree/FAQs/FAQs.cshtml
@model ISM.WebApp.ViewModels.FAQIndexViewModel
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@using ISM.WebApp.Constant;
@{
    var sessionUser = JsonConvert.DeserializeObject<Account>(Context.Session.GetString(LoginConst.SessionKeyName));
    if (sessionUser.role_name == "Degree")
    {
        ViewData["Title"] = "Pre-Approval Visa Page";
        Layout = "~/Views/Shared/_DegreeStudentLayout.cshtml";
    }
    else if (sessionUser.role_name == "Mobility")
    {
        ViewData["Title"] = "Pre-Approval Visa  Page";
        Layout = "~/Views/Shared/_MobilityStudentLayout.cshtml";
    }
}

<h1 style="text-align: center;">FAQs</h1>
<div style="height: 50px;">
    <div class="dropdown_search">
        <button type="button" onclick="myFunction1()" style="width:80px;border-radius:10px" class="btn btn-primary">Search</button>
        <div id="myDropdown_search" class="dropdown-content_search" style="height: 150px; margin-top: 10px;">
            <form id="searchForm" asp-controller="FAQ" asp-action="Index" method="get" style="width: 320px;">
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Question:</label>
                    <input maxlength="250" type="text" name="question" style="width: 200px; border-radius: 5px;" value="@Model.question">
                </div>
                <div class="form-group row">
                    <label style="margin-left: 30px; font-weight: bold; width:100px;">Answer:</label>
                    <input maxlength="250" type="text" name="answer" style="width: 200px; border-radius: 5px;" value="@Model.answer">
                </div>
                <input type="hidden" name="page" id="inputPage" />
                <button id="searchButton" type="submit" onclick="disableButton('searchButton'); search(1);" class="btn btn-info" style="margin-left: 150px;">Search</button>
            </form>
        </div>
    </div>
</div>
<br>
<br>
<div class="table-scroll">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">No</th>
                <th scope="col">Question</th>
                <th scope="col">Answer</th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.faqs.Count; i++)
            {
                <tr>
                    <td>
                        @(i+1)
                    </td>
                    <td>
                        @Model.faqs[i].question
                    </td>
                    <td>
                        @Model.faqs[i].answer
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    @Html.Raw(ISM.WebApp.Utils.PagingUtils.pager(Model.totalPage, Model.page, 3))
</div>

<script>function myFunction1() {
        document.getElementById("myDropdown_search").classList.toggle("show_search_insurance");
    }
    function filterFunction() {
        var input, filter, ul, li, a, i;
        input = document.getElementById("myInput");
        filter = input.value.toUpperCase();
        div = document.getElementById("myDropdown_search");
        a = div.getElementsByTagName("a");
        for (i = 0; i < a.length; i++) {
            txtValue = a[i].textContent || a[i].innerText;
            if (txtValue.toUpperCase().indexOf(filter) > -1) {
                a[i].style.display = "";
            } else {
                a[i].style.display = "none";
            }
        }
    }</script>